name: better_clock_flutter_app
description: "A better alternative to default Android Clock App"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

lint_staged:
  "lib/**.dart": dart format -o show lib && dart fix --apply

dependencies:
  alarm: ^5.1.2
  alphabet_list_view: ^1.1.0
  analog_clock: ^0.1.1
  animate_do: ^4.2.0
  async_queue: ^2.0.0
  audioplayers: ^6.1.0
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_autostart: ^0.0.2
  flutter_hooks: ^0.20.5
  flutter_swipe_button: ^2.1.3
  fquery: ^1.4.0-beta.1
  go_router: ^15.1.1
  intl: ^0.20.2
  isar: 4.0.0-dev.14
  isar_flutter_libs: 4.0.0-dev.14
  loading_animation_widget: ^1.2.1
  path_provider: ^2.1.3
  permission_handler: ^12.0.0+1
  pulsator: ^1.0.0+2
  shared_preferences: ^2.3.2
  timezone: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  husky: ^0.1.7
  lint_staged: ^0.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/ringtones/
